---
title: "Linmod_w_prediction"
author: "Michael Recinos"
output: html_document
date: "2024-04-09"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

require(tidyverse)
require(tigerstats)
require(lubrudate)

data <- read.csv(file="https://onlinestatbook.com/case_studies_rvls/physical_strength/data.txt",sep="",header=TRUE)  
```


## Model 1 is SIMS~ARM
### scattered plot

```{r}
basicAMR <- ggplot(data,aes(y=SIMS,x=ARM))
```

```{r}
basicAMR + geom_point() + ggtitle ("SIMS vs ARM") + theme(plot.title = element_text(hjust =  0.5, size = 20)) + geom_smooth(method = lm)
```

```{r}
model.1 <- lm(SIMS~ARM, data=data)
```


```{r}
target<-data.frame(ARM = 88, GRIP = 94)
```

```{r}
predict(model.1, target, interval=c("prediction"))
```


## Model 2 is SIMS~GRIP
### scattered plot


```{r}
basicGRIP <- ggplot(data,aes(y=SIMS,x=GRIP))
```

```{r}
basicGRIP + geom_point() + ggtitle ("SIMS vs GRIP") + theme(plot.title = element_text(hjust =  0.5, size = 20)) + geom_smooth(method = lm)
```

```{r}
model.2 <- lm(SIMS~GRIP, data=data)
```


```{r}
predict(model.2, target, interval=c("prediction"))
```


## Model 3 is SIMS~ARM+GRIP
### scattered plot


```{r}
basicSIMS <- ggplot(data,aes(y=SIMS,x=GRIP))
```

```{r}
basicSIMS + geom_point() + ggtitle ("SIMS vs GRIP") + theme(plot.title = element_text(hjust =  0.5, size = 20)) + geom_smooth(method = lm)
```


